demo/src/demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from post.views import listview

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^', listview, {'template_name' : 'listing.html'}, name="home"),
]

demo/src/post/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import PostView, delete_post

urlpatterns = [
    url(r'^(?P<id>\d+)/$', PostView.as_view(template_name='post.html'), name="update_post"),
    url(r'^$', PostView.as_view(template_name='post.html'), name="post"),
    url(r'^(?P<id>\d+)/delete/$', delete_post, {'template_name' : 'delete.html'}, name="delete"),
]

demo/src/post/models.py
from django.db import models
from django.utils.encoding import smart_text


PRIVACY_TYPE = (
	("PR" , "Private"),
	("PB" , "Public"),
	)
# Create your models here.
class Post(models.Model):
	post_id = models.BigAutoField(primary_key=True)
	title = models.CharField(max_length=100)
	content = models.TextField(null=True, blank=True)
	post_type = models.CharField(max_length=3, choices=PRIVACY_TYPE, default=PRIVACY_TYPE[0][0])

	class Meta:
		db_table = "post_table"

	def __str__(self):
		return smart_text(self.post_id)

demo/src/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['post_id', 'title', 'content', 'post_type']

demo/src/post/views.py
from django.shortcuts import render, reverse, get_object_or_404, HttpResponseRedirect
from django.views.generic.base import TemplateView
from .forms import PostForm
from .models import Post
# Create your views here.

# For this case, I simply raise Http404 error if the post does not exist. It can also be treated another way by redirection.
# For example, 
#	if not Post.objects.get(pk=id):
#		HttpResponseRedirect("namespace:name")
# The parameter namespace is the app name set in project urls.py, name is the routing name set in app urls.py
class PostView(TemplateView):
	form = PostForm

	def post(self, request, id=None, *args, **kwargs):
		if id:
			post_obj = get_object_or_404(Post, pk=id)
			form = self.form(request.POST, instance=post_obj)
		else:
			form = self.form(request.POST)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect("/")

		context={
			"form" : form,
		}
		return render(request, self.template_name, context)

	def get(self, request, id=None, *args, **kwargs):
		
		if id:
			post_obj = get_object_or_404(Post, pk=id)
			form = self.form(instance=post_obj)
		else:
			form = self.form()
		print(id)
		context={
			"form" : form,
			"id" : id,
		}
		return render(request, self.template_name, context)

def listview(request, *args, **kwargs):
	post_obj = Post.objects.all()
	print(post_obj)
	context = {
		"post" : post_obj,
	}
	return render(request, kwargs["template_name"], context)

def delete_post(request, id, *args, **kwargs):
	post_obj = get_object_or_404(Post, pk=id)
	if request.POST:
		post_obj.delete()
		return HttpResponseRedirect("/")

	context = {
		"form" : post_obj,
	}
	return render(request, kwargs["template_name"], context)

demo/src/post/templates/delete.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Delete {{ form.title }}</h1>
	<form method="POST" novalidate>{% csrf_token %}
	Are you sure you want to delete this post?
		<input type="submit" value="Yes">
	</form>
	<a href="{% url 'home' %}">Cancel</a>
</body>
</html>

demo/src/post/templates/listing.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<style type="text/css">
	span{
		padding:0 16px;
	}
</style>
{% if not post %}
	<h1>No post found</h1>
{% endif %}
<a href="{% url 'post:post' %}">Create a new post!</a>
{% for p in post %}
	<ul>
		<li><span><a href="{% url 'post:update_post' id=p.post_id %}">{{ p.title}} </a></span><span><a href="{% url 'post:delete' id=p.post_id %}">Delete</a></span></li>
	</ul>

{% endfor %}
	
</body>
</html>

demo/src/post/templates/post.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="POST" novalidate>{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit">
	</form>
	
</body>
</html>